name: Generate docs

on: [push]

jobs:
  gen:
    name: Generate and deploy docs
    runs-on: ubuntu-latest  

    steps:
      - uses: actions/checkout@v2
      - uses: iffy/install-nim@v4.1.1
      - name: Generate
        run: |
          nimble install -d -y
          nim doc --git.url:https://github.com/${{ github.GITHUB_REPOSITORY }} --git.commit:main --project --outdir:docs src/*.nim
          echo "<meta http-equiv=\"Refresh\" content=\"0; url='niprefs.html'\" />" >> docs/index.html
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
