
name: Check and test niprefs in windows-latest

on:
  pull_request:
    branches: [main, dev]
  push:
    branches: [main, dev]

jobs:
  default:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: iffy/install-nim@v4.1.1
      - run: nimble install -y
      - run: nimble test
